theme: minima
title: Portfolio
author: Kairosite
description: description text here
header_pages:
  - about.md
minima:
  social_links:
    - { platform: github,  user_url: "https://github.com/Kairosite" }
